version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata01:
    external: false

networks:
  elastic:
    driver: bridge
